#!/bin/sh
chmod -R go-w /System/Library/Extensions/SATSMARTDriver.kext 
chown -R root:wheel /System/Library/Extensions/SATSMARTDriver.kext 
# Remove old version
rm -rf /System/Library/Extensions/SATSMARTLib.plugin
kextutil /System/Library/Extensions/SATSMARTDriver.kext
exit 0
