#!/bin/sh
chmod -R go-w /System/Library/Extensions/SATSMARTDriver.kext 
chown -R root:wheel /System/Library/Extensions/SATSMARTDriver.kext 
chmod -R go-w /System/Library/Extensions/SATSMARTLib.plugin
chown -R root:wheel /System/Library/Extensions/SATSMARTLib.plugin
kextutil /System/Library/Extensions/SATSMARTDriver.kext
exit 0
